#!/bin/sh
#
# Copyright (C) 2025 Dustin <huangyanjie@x-speed.com.cn>
#

update_ats() {
    if [[ -f /factory_env ]]; then
        rootdev_f=$(cat /factory_env | awk -F 'rootdev=' '{print$2}' | awk '{print $1}')
        atsdev_f=$(cat /factory_env | awk -F 'ats_label=' '{print$2}' | awk '{print $1}')
    else
        rootdev_f=""
        atsdev_f=""
    fi

    rootdev_c=$(cat /proc/cmdline | awk -F 'rootdev=' '{print$2}' | awk '{print $1}')
    atsdev_c=$(cat /proc/cmdline | awk -F 'ats_label=' '{print$2}' | awk '{print $1}')

    rootdev=${rootdev_f:-$rootdev_c}
    ats_dev=${atsdev_f:-$atsdev_c}

    if [[ -n "$ats_dev" ]]; then
        atsdev=$(blkid | grep ${ats_dev} | awk -F : '{print $1}')
    fi

    blkdev=${atsdev:-$rootdev}
    board=$(dmidecode -t0 | grep Version: | awk '{print $2}' | cut -d'_' -f2 | tr 'A-Z' 'a-z')
    echo "Update ATS: [${board}] ats_label dev [${atsdev}] rootdev [${rootdev}] finaldev [${blkdev}] !" | tee /dev/kmsg >/dev/null

    if [ -b "$blkdev" ]; then
        mount "$blkdev" /mnt
        file="/mnt/board/${board}/rename_network.sh"
        if [ -e "$file" ]; then
            echo "Rename_network: Starting ${file} script !" | tee /dev/kmsg >/dev/null
            chmod +x "$file"
            "$file"
        else
            file="/mnt/rename_network.sh"
            if [ -e "$file" ]; then
                echo "Rename_network: Starting ${file} script !" | tee /dev/kmsg >/dev/null
                chmod +x "$file"
                "$file"
            fi
        fi
        file="/mnt/ate/ateinit.sh"
        if [ -e "$file" ]; then
            echo "Ateinit: Starting ${file} script !" | tee /dev/kmsg >/dev/null
            chmod +x "$file"
            "$file"
        fi
        umount /mnt
    fi
}

for if_name in $(ls /sys/class/net | grep -v can | grep -v usb | grep -v wlan | grep -vE '^(lo)' | sort -V); do
    ifconfig $if_name down
done

update_ats

for if_name in $(ls /sys/class/net | grep -v can | grep -v usb | grep -v wlan | grep -vE '^(lo)' | sort -V); do
    ifconfig $if_name up
done

exit 0
