#!/bin/sh
#
# Copyright (C) 2025 Dustin <huangyanjie@x-speed.com.cn>
#

update_ats() {
    rootdev_f=$(cat /factory_env | awk -F 'rootdev=' '{print$2}' | awk '{print $1}')
    rootdev_c=$(cat /proc/cmdline | awk -F 'rootdev=' '{print$2}' | awk '{print $1}')

    atsdev_f=$(cat /factory_env | awk -F 'ats_label=' '{print$2}' | awk '{print $1}')
    atsdev_c=$(cat /proc/cmdline | awk -F 'ats_label=' '{print$2}' | awk '{print $1}')

    if [ -z "${rootdev_f}" ]; then
        rootdev=${rootdev_c}
    else
        rootdev=${rootdev_f}
    fi

    if [ -z "${atsdev_f}" ]; then
        ats_dev=${atsdev_c}
    else
        ats_dev=${atsdev_f}
    fi
    atsdev=$(blkid | grep ${ats_dev} | awk -F : '{print $1}' | awk -F / '{print $NF}' | sed 's/[0-9]*$//;s/p$//')

    if [ -z "${atsdev}" ]; then
        blkdev=${rootdev}
    else
        blkdev=${atsdev}
    fi
    echo "Update ATS: atsdev [${atsdev}] rootdev [${rootdev}] finaldev [${blkdev}]" | tee /dev/kmsg

    if [ -b "$blkdev" ]; then
        mount "$blkdev" /mnt
        file="/mnt/rename_network.sh"
        if [ -e "$file" ]; then
            echo "rename_network: Starting ${file} script !" | tee /dev/kmsg
            chmod +x "$file"
            . "$file"
        fi
        file="/mnt/ate/ateinit.sh"
        if [ -e "$file" ]; then
            echo "ateinit: Starting ${file} script !" | tee /dev/kmsg
            chmod +x "$file"
            . "$file"
        fi
        umount /mnt
    fi
}

for if_name in $(ls /sys/class/net | grep -E '^(GE|eth)'); do
    ifconfig $if_name down
done

TARGET=$(cat /etc/os-release | grep -w 'OPENWRT_BOARD' | cut -d= -f2 | tr -d '"')
# xspeed/linux4197_d2000 xspeed/linux419246_e2000
# xspeed/lsdk1903_autotest xspeed/lsdk1903_NH15 xspeed/lsdk1903_NH25_aut xspeed/lsdk1903_NZXX_ate
# xspeed/lsdk2012_autotest xspeed/lsdk2012_nz60_aut
# xspeed/kernel419232_raxx xspeed/kernel419232_ra03

case "$TARGET" in
xspeed/lsdk*)
    n=0
    i=$(ls /sys/class/net | grep -E '^(GE|eth)' | wc -l)
    while [ $n -le $i ]; do

        name="eth""$n"
        newname="GE""$n"
        ip link set $name name $newname
        let ++n
    done
    ;;
*) ;;
esac

update_ats

for if_name in $(ls /sys/class/net | grep -E '^(GE|eth)'); do
    ifconfig $if_name up
done

exit 0
